# Cloudflare Pages project configuration
name = "kkn-hub"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kkn-hub-db"
database_id = "d4551c5d-7d4a-462f-b4b3-8119ccaefb22"
